FROM python:3.11

WORKDIR /app

COPY requirements.txt .
COPY requirements-dev.txt .


RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY ./app .

EXPOSE 5000 5678

ENV FLASK_APP=main.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=production

CMD ["flask", "run", "--host=0.0.0.0", "--reload", "-Xfrozen_modules=off",]
