-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."influencers" add column "is_followed" boolean
--  null default 'False';
