-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP TABLE IF EXISTS public.contents_assertion CASCADE;
-- DROP TABLE IF EXISTS public.assertions_content CASCADE;
-- DROP TABLE IF EXISTS public.content_relationship CASCADE;
-- DROP TABLE IF EXISTS public.assertions CASCADE;
-- DROP TABLE IF EXISTS public.content CASCADE;
